### **1. What does Pandas stand for?** ###

**Answer-** Pandas stands for either:
- Panel Data 
- Python Data Analysis

### **2. What are the 2 collections used in Pandas?** ###

**Answer-** 
- Series
- Data Frames
### **3. Name 4 things Pandas can do for us.** ###

**Answer-** 
- Data Cleaning
- Data Filling
- Loading & Saving Data
- Data Visualization
### **4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?** ###

**Answer-** inplace = True

### **5. What is a CSV?** ###

**Answer-** CSV(comma separated files) is basically a plain text file format that contains data.

### **6. When cleaning data what values do we not like in our data?** ###

**Answer-** We do not like missing values.

In [1]:
#Question 7
import numpy as np
import pandas as pd
array1 = np.array([2,3,2])
print(array1)

[2 3 2]

In [2]:
#Questionn 8
import copy
x = np.linspace(0, 20, num=6)
print("Array x ...", x)
# 9. Make a Deep Copy of the above array
x1 = copy.deepcopy(x)
print('DeepCopy Array',x1)

Array x ... [ 0.  4.  8. 12. 16. 20.]
DeepCopy Array [ 0.  4.  8. 12. 16. 20.]

In [3]:
#Question 15

ingredients = pd.Series (['Flour', 'Milk', 'Eggs', 'Spam'], name='Ingredients')
quantity = pd.Series([4,1,2,1], name= 'Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name= 'Unit')

Dinner = pd.concat([ingredients, quantity, unit], axis = 1)
Dinner

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [4]:
#Question 16

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
students = pd.DataFrame(studentData)
students

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [5]:
#Question 17 
Desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
students.insert(7,'Desserts',Desserts,True)
students

,Name,Height,Qualification,address,Age,Pets,sport,Desserts
0,Jai,5.1,Msc,Delhi,21,Dog,Darts,ice cream
1,janusha,6.2,MA,Doha,23,Bunny,Basketball,Cashew Fudge
2,Gaurav,5.1,Msc,Chennai,24,Chinchilla,PaddleBoarding,waffels
3,Anuj,5.2,Msc,Dakhar,21,Parrot,Cricket,Carrot Halwa

In [6]:
#Question 18
students.sort_values(by = ['Name','address'], ascending = [True, True] )

,Name,Height,Qualification,address,Age,Pets,sport,Desserts
3,Anuj,5.2,Msc,Dakhar,21,Parrot,Cricket,Carrot Halwa
2,Gaurav,5.1,Msc,Chennai,24,Chinchilla,PaddleBoarding,waffels
0,Jai,5.1,Msc,Delhi,21,Dog,Darts,ice cream
1,janusha,6.2,MA,Doha,23,Bunny,Basketball,Cashew Fudge

In [7]:
#Question 19
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
df

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [8]:
#Question 20

vegdf = pd.DataFrame({'Vegetables': ['Carrot', 'Broccoli', 'Onion', 'Tomato'],
                      'Colors': ['Orange', 'Green', 'Yellow', 'Grey']}, columns=['Vegetables', 'Colors'])
vegdf
#vegdf.to_csv('Vegetables.csv')

  Vegetables  Colors
0     Carrot  Orange
1   Broccoli   Green
2      Onion  Yellow
3     Tomato    Grey

In [9]:
vegdf['Colors'] = vegdf['Colors'].replace('Grey','Red')
vegdf.to_csv('NewVegColor.csv')
vegdf

  Vegetables  Colors
0     Carrot  Orange
1   Broccoli   Green
2      Onion  Yellow
3     Tomato     Red